### ISSUE TITLE
ambiguous characters 

### ISSUE THREAD

**Issue by smirarab** [chaoszhang/TAPER#2]
Make sure ambiguous characters are dealt with intelligently, both for DNA and AA, but especially for DNA. Not sure what the best approach is, but is worth considering. I don't think treating them as a new character is the right approach. We can think about the best treatment.

**Comment by chaoszhang** [comment]
Right now I am treating ambiguous characters as dashes.

**Comment by chaoszhang** [comment]
We will remove such character the same way as a dash after scoring the columns.
