### ISSUE TITLE
Can MAFFT be used after processing data with TAPER?

### ISSUE THREAD

**Issue by ZhiqiongMo** [chaoszhang/TAPER#8]
I used TAPER to process my data matrix, and now I intend to extract specific samples from the TAPER output for phylogenetic analysis.
I would like to know if the extracted data can be realigned using MAFFT?

Thanks in advance

**Comment by chaoszhang** [comment]
Go ahead. I don't see any problem with it. :)

ZhiqiongMo ***@***.***> 于 2023年9月9日周六 01:46写道：

**Comment by ZhiqiongMo** [comment]
> 

Thank you very much! It will be of great help to my analysis.
